### ISSUE TITLE
Investigate python-markdown2 support

### ISSUE THREAD

**Issue by tony** [Alir3z4/django-markwhat#13]
https://github.com/trentm/python-markdown2

**Comment by Alir3z4** [comment]
@tony thanks for mentioning that.

Do you think we should replace `Markdown` with `markdown2` ? The only thing I figured from it docs is performance(which is really good).

We can provide a `markdown2` template tag and have it with the other one, or just totally replace it?

What are your thoughts ?

**Comment by tony** [comment]
There is a lot of duplication across the board in markup support in django:

* https://github.com/bartTC/django-markup (does what django-markwhat does)

Markdown-only projects:

* https://github.com/klen/django_markdown (goes well beyond tags)
* https://github.com/svetlyak40wt/django-markdown2
* https://github.com/trentm/django-markdown-deux

I have half a mind to branch https://github.com/klen/django_markdown and
try abstracting it to handle docutils / other filters also.

My theory is after django removed the markup features from core in 1.4, the
lines of communication got cut pretty much. I think it's a matter of who
wants to step forward on it.

@Alir3z4, @klen, @trentm, @svetlyak40wt, @bartTC: are you aware of the
other projects?  Would you be open to consolidating your efforts into one
project to prevent duplication and have a united front on this?

**Comment by svetlyak40wt** [comment]
Well, my project isn't evolving anymore and fulfills all my needs.

**Comment by trentm** [comment]
I'm easy. :) I'm not using Django that much currently.

**Comment by nikolas** [comment]
django-markwhat should support at least one python markdown library that implements [CommonMark](http://commonmark.org/). The only one that I know of is here: https://pypi.python.org/pypi/CommonMark. I'll make a PR to add a filter tag for it.

**Comment by nikolas** [comment]
The python Markdown library seems to work fine from my experience .. what issues does Markdown2 solve?

**Comment by svetlyak40wt** [comment]
As I remember, markdown2 supports more extensions.

**Comment by Alir3z4** [comment]
If `markdown2` supports more extensions then it might be a good option. Also it says that it's fast.

Although I still have in mind that:

> We can provide a markdown2 template tag and have it with the other one, or just totally replace it?

**Comment by trentm** [comment]
That claim of 'fast' might no longer be true compared to Python-Markdown, FWIW.

**Comment by Alir3z4** [comment]
> That claim of 'fast' might no longer be true compared to Python-Markdown, FWIW.

Well if it supports more extensions still it would be a good idea to have an extra tag that uses markdown2 for rendering I guess.

**Comment by nikolas** [comment]
closing this for now
