### ISSUE TITLE
'latest version' on pypi is incorrect

### ISSUE THREAD

**Issue by nikolas** [Alir3z4/django-markwhat#21]
I'm not sure how we would resolve this, but on the pypi page: https://pypi.python.org/pypi/django-markwhat/1.3

The 'latest version' points to version 2014.9.20, when it should be version 1.3.

**Comment by Alir3z4** [comment]
I think by removing the old versions the problem will be solved ?

**Comment by nikolas** [comment]
Possibly, but keep in mind that anyone's packages that rely on version `2014.9.20` with pip will then break until they update to `1.3`. It may be the only option, though.

**Comment by Alir3z4** [comment]
We can still get back to the date based version numbering..

Just saying...

**Comment by nikolas** [comment]
Yeah, true. I think the bottom line is that we should pick one version scheme or the other, even if that means removing a version from the archive. Having the two schemes is confusing, and messes up pypi and automated tools like `piprot`.

I would prefer the incrementing version scheme like `1.3`, `1.4`, because it's more typical of projects on pypi, and we actually should remove version `2014.9.20` from pypi. What do you think?

**Comment by Alir3z4** [comment]
Holly miow miow, such a shame, I didn't know about `piprot`.

Your comment, make sense, I'll remove the older versions from `pypi` keep using incrementing version scheme.

Thanks ;)

**Comment by Alir3z4** [comment]
@nikolas I've removed the date scheme based versions from the pypi.
Soon I'll release a new version with commonMark changes ;).
