### ISSUE TITLE
Pyup & Doppins ?

### ISSUE THREAD

**Issue by Alir3z4** [Alir3z4/django-markwhat#46]
Hey @nikolas, do you know how we can disable one of these ? they both send upgrade pull requests that are good but I don't remember activating them and now both of them send pull requests at the same time.

**Comment by nikolas** [comment]
sorry i will disable doppins! and pyup too if you want

**Comment by Alir3z4** [comment]
No both are good.
It's just both of them do the same job right?

**Comment by Alir3z4** [comment]
Oh I just found out Pyup keeps security updates and doppins does normal upgrades,
Awesome then, @nikolas keep both of them please.

Thanks for activating them ;)

**Comment by nikolas** [comment]
they both do the same upgrades, i think pyup just alerts you of any security issues as well

**Comment by Alir3z4** [comment]
Yeah, it seems so. Let's keep both of them, I guess they're doing good.

**Comment by nikolas** [comment]
well what i mean is we really don't need both. i've already disabled doppins, but you can always re-enable it if you want at doppins.com.

**Comment by Alir3z4** [comment]
Oh, ok,
That makes sense ;)
