### ISSUE TITLE
Incompatible with Markdown 3.0

### ISSUE THREAD

**Issue by thraxil** [Alir3z4/django-markwhat#77]
Markdown 3.0 "deprecated" the `enable_attributes` and `safe_mode` parameters:

* https://github.com/Python-Markdown/markdown/blob/master/docs/change_log/release-3.0.md#enable_attributes-keyword-deprecated
* https://github.com/Python-Markdown/markdown/blob/master/docs/change_log/release-3.0.md#safe_mode-and-html_replacement_text-keywords-deprecated

It also deprecated positional arguments, and this is causing an exception:

* https://github.com/Python-Markdown/markdown/blob/master/docs/change_log/release-3.0.md#positional-arguments-deprecated

It's an easy fix. I'll put in a PR in a bit.

**Comment by trevoriancox** [comment]
Yes, with:
- django-markwhat==1.4
- Markdown==3.0.1

the markdown filter gives me:
`markdown() takes 1 positional argument but 2 were given`

**Comment by Alir3z4** [comment]
Fixed in #78
